### ISSUE TITLE
ssm-agent can't proceed further from "Starting"

### ISSUE THREAD

**Issue by sbsoo111** [aws/amazon-ssm-agent#249]
Hi All

I have stucked with this error on my aws private subnet that i'm trying to connect my EC2 instance into the aw system manager. It work fine by having public subnet instance connected, but not in private subnet. step i carry when troubleshoot:
1. already setup the private dns link.
2. tried by set the endpoint in amazon-ssm-agent.json
3. reinstall the ssm agent
4. set the debug log but still can't get any clue from the error log as below.
5. i can telnet 443 from the instance to the vpc endpoint of ec2, ec2message, ssm, ssmmessage.
6. allow all incoming and outgoing from the security group of the endpoint as well as the ec2 instance.

below are the message i got if i manually run the command from cmd, i tried run the command from the instance in public subnet and the output is pretty quick without any error.

C:\Program Files\Amazon\SSM>amazon-ssm-agent
2020/01/05 15:12:18 Failed to load instance info from vault. RegistrationKey does not exist.
Initializing new seelog logger
New Seelog Logger Creation Complete
2020-01-05 15:12:18 DEBUG Start File Watcher On: C:\Program Files\Amazon\SSM\seelog.xml
2020/01/05 15:12:18 Found config file at C:\Program Files\Amazon\SSM\amazon-ssm-agent.json.
Applying config override from C:\Program Files\Amazon\SSM\amazon-ssm-agent.json.
2020/01/05 15:12:18 processing appconfig overrides
2020-01-05 15:12:18 DEBUG Start Watcher on directory: C:\Program Files\Amazon\SSM
2020-01-05 15:12:18 INFO Windows Only: Job object creation on SSM agent successful
2020-01-05 15:12:18 DEBUG Current proxy environment variables: https_proxy:;http_proxy:;no_proxy:
2020-01-05 15:12:18 INFO Getting IE proxy configuration for current user: The operation completed successfully.
2020-01-05 15:12:18 DEBUG IE proxy configuration for current user: proxy:,bypass:,enabled:false,automatically detect proxy settings:true,automatic configuration script:
2020-01-05 15:12:18 INFO Getting WinHTTP proxy default configuration: The operation completed successfully.
2020-01-05 15:12:18 DEBUG WinHTTP proxy default configuration: proxy:,bypass:
2020-01-05 15:12:18 DEBUG ParseProxySettings result: http_proxy:<nil>,https_proxy:<nil>
2020-01-05 15:12:18 DEBUG New proxy environment variables: https_proxy:;http_proxy:;no_proxy:
2020-01-05 15:12:18 INFO Proxy environment variables:
2020-01-05 15:12:18 INFO http_proxy:
2020-01-05 15:12:18 INFO https_proxy:
2020-01-05 15:12:18 INFO no_proxy:

C:\Program Files\Amazon\SSM>amazon-ssm-agent
2020/01/05 15:14:03 Failed to load instance info from vault. RegistrationKey does not exist.
Initializing new seelog logger
New Seelog Logger Creation Complete
2020-01-05 15:14:03 DEBUG Start File Watcher On: C:\Program Files\Amazon\SSM\seelog.xml
2020/01/05 15:14:03 Found config file at C:\Program Files\Amazon\SSM\amazon-ssm-agent.json.
Applying config override from C:\Program Files\Amazon\SSM\amazon-ssm-agent.json.
2020/01/05 15:14:03 processing appconfig overrides
2020-01-05 15:14:03 DEBUG Start Watcher on directory: C:\Program Files\Amazon\SSM
2020-01-05 15:14:03 INFO Windows Only: Job object creation on SSM agent successful
2020-01-05 15:14:03 DEBUG Current proxy environment variables: https_proxy:;http_proxy:;no_proxy:
2020-01-05 15:14:03 INFO Getting IE proxy configuration for current user: The operation completed successfully.
2020-01-05 15:14:03 DEBUG IE proxy configuration for current user: proxy:,bypass:,enabled:false,automatically detect proxy settings:true,automatic configuration script:
2020-01-05 15:14:03 INFO Getting WinHTTP proxy default configuration: The operation completed successfully.
2020-01-05 15:14:03 DEBUG WinHTTP proxy default configuration: proxy:,bypass:
2020-01-05 15:14:03 DEBUG ParseProxySettings result: http_proxy:<nil>,https_proxy:<nil>
2020-01-05 15:14:03 DEBUG New proxy environment variables: https_proxy:;http_proxy:;no_proxy:
2020-01-05 15:14:03 INFO Proxy environment variables:
2020-01-05 15:14:03 INFO http_proxy:
2020-01-05 15:14:03 INFO https_proxy:
2020-01-05 15:14:03 INFO no_proxy:
2020-01-05 15:17:30 ERROR Agent crashed with message runtime error: invalid memory address or nil pointer dereference!
2020-01-05 15:17:30 ERROR runtime error: invalid memory address or nil pointer dereference: goroutine 1 [running]:
runtime/debug.Stack(0xc0001e2de0, 0x101361c, 0x1e)
        /opt/brazil-pkg-cache/packages/GoLang/GoLang-1.12.25.0/RHEL5_64/DEV.STD.PTHREAD/build/lib/src/runtime/debug/stack.go:24 +0xa4
main.run.func1(0x1293040, 0xc0001e2de0)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/agent/agent.go:131 +0xd1
panic(0xeb2300, 0x1a47db0)
        /opt/brazil-pkg-cache/packages/GoLang/GoLang-1.12.25.0/RHEL5_64/DEV.STD.PTHREAD/build/lib/src/runtime/panic.go:522 +0x1c3
github.com/aws/amazon-ssm-agent/agent/platform.(*EC2MetadataClient).retrieveInfoWithToken(0xc00013a8e8, 0xc000200800, 0x40, 0x0, 0x1270980, 0xc0002b7da0)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_metadata.go:192 +0x1e6
github.com/aws/amazon-ssm-agent/agent/platform.(*EC2MetadataClient).readResourceFromMetaDataV2(0xc00013a8e8, 0xc000200800, 0x40, 0x0, 0xc000200800, 0x40)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_metadata.go:168 +0x4a
github.com/aws/amazon-ssm-agent/agent/platform.EC2MetadataClient.ReadResource(0x127ad40, 0xc0001dbc50, 0x0, 0x0, 0x1021bce, 0x2a, 0x0, 0x0, 0x0, 0x0, ...)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_metadata.go:148 +0xe5
github.com/aws/amazon-ssm-agent/agent/platform.EC2MetadataClient.InstanceIdentityDocument(0x127ad40, 0xc0001dbc50, 0x0, 0x0, 0x0, 0x1c8c800, 0xc0001c5740)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_metadata.go:118 +0x78
github.com/aws/amazon-ssm-agent/agent/platform.instanceDynamicData.Region(0xc0001e2240, 0x0, 0x0, 0x1c8c800, 0xc0001c5740)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_info_deps.go:114 +0x54
github.com/aws/amazon-ssm-agent/agent/platform.fetchRegion(0x8, 0x1043208, 0x1a76230, 0xc0000268a0)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_info.go:249 +0x102
github.com/aws/amazon-ssm-agent/agent/platform.Region(0x0, 0x0, 0x0, 0x0)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/platform/instance_info.go:111 +0x94
github.com/aws/amazon-ssm-agent/agent/sdkutil.AwsConfig(0xf13640)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/sdkutil/awsconfig.go:42 +0xdd
github.com/aws/amazon-ssm-agent/agent/ssm.NewService(0xc00013b8e0, 0x1288b80)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/build/private/src/github.com/aws/amazon-ssm-agent/agent/ssm/service.go:91 +0x4c
main.start(0x1293040, 0xc0001e2de0, 0xc000026550, 0xc000026560, 0x1, 0x0, 0x120, 0x6, 0x10)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/agent/agent.go:71 +0x3f4
main.run(0x1293040, 0xc0001e2de0)
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/agent/agent.go:136 +0x97
main.main()
        /local/p4clients/pkgbuild-fjgXa/workspace/src/Amazon-ssm-agent/agent/agent_windows.go:75 +0x2f7

**Comment by sbsoo111** [comment]
i found the issue that had related to routing table that inherited from the previous image, reroute everything from the old route gateway ip then everything back to charm.

lesson learned: always check the route table if your AMI images is done from the different subnet

**Comment by sbsoo111** [comment]
issued resolved
