### ISSUE TITLE
Agent patch scan/install failing on Debian 11

### ISSUE THREAD

**Issue by mrleerkotte** [aws/amazon-ssm-agent#453]
Hi folks,

I'm trying to deploy the SSM agent on Debian 11, the installation and initial reporting to AWS works as intended. But when I try to execute a patch scan or install it results in a failure. I tried to see if I was missing some system requirements but as far as I can tell this is not the case.

```/usr/bin/python3
/usr/bin/python2.7
/usr/bin/apt-get
Reading package lists...
Building dependency tree...
Reading state information...
python3-apt is already the newest version (2.2.1).
The following packages were automatically installed and are no longer required:
  linux-image-4.9.0-16-amd64 linux-image-5.10.0-11-amd64
  linux-image-5.10.0-9-amd64
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 27 not upgraded.
Using python binary: 'python3'
Using Python Version: Python 3.9.2
07/07/2022 15:52:27 root [INFO]: Downloading payload from https://s3.dualstack.eu-central-1.amazonaws.com/aws-ssm-eu-central-1/patchbaselineoperations/linux/payloads/patch-baseline-operations-1.87.tar.gz
07/07/2022 15:52:29 root [INFO]: Attempting to import entrance file os_selector
07/07/2022 15:52:29 root [INFO]: Running with snapshot id =  and operation = Install
07/07/2022 15:52:29 botocore.credentials [INFO]: Found credentials in shared credentials file: /root/.aws/credentials
07/07/2022 15:52:29 root [ERROR]: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
    patch_snapshot = _get_snapshot_with_client(ssm_client, instance_id, snapshot_id, baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 418, in _get_snapshot_with_client
    return ssm_client.get_deployable_patch_snapshot_for_instance(
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
07/07/2022 15:52:29 root [ERROR]: Error loading entrance module.
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
    patch_snapshot = _get_snapshot_with_client(ssm_client, instance_id, snapshot_id, baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 418, in _get_snapshot_with_client
    return ssm_client.get_deployable_patch_snapshot_for_instance(
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 165, in execute
    exit(   entrance_module.execute(*argv))
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 54, in execute
    common_os_selector_methods.fetch_snapshot(operation_type, instance_id, region, reboot_option, document_step,
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 280, in fetch_snapshot
    snapshot_info = _get_snapshot_info(instance_id, snapshot_id, region, baseline_override_dict)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 134, in _get_snapshot_info
    raise PatchManagerError("Unsupported Operating System", ExitCodes.SNAPSHOT_UNSUPPORTED_OS, e)
patch_common.exceptions.PatchManagerError: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
07/07/2022 15:52:29 root [ERROR]: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
    patch_snapshot = _get_snapshot_with_client(ssm_client, instance_id, snapshot_id, baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 418, in _get_snapshot_with_client
    return ssm_client.get_deployable_patch_snapshot_for_instance(
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 165, in execute
    exit(   entrance_module.execute(*argv))
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 54, in execute
    common_os_selector_methods.fetch_snapshot(operation_type, instance_id, region, reboot_option, document_step,
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 280, in fetch_snapshot
    snapshot_info = _get_snapshot_info(instance_id, snapshot_id, region, baseline_override_dict)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 134, in _get_snapshot_info
    raise PatchManagerError("Unsupported Operating System", ExitCodes.SNAPSHOT_UNSUPPORTED_OS, e)
patch_common.exceptions.PatchManagerError: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
07/07/2022 15:52:29 root [ERROR]: unsupported operand type(s) for %: 'NoneType' and 'tuple'
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 418, in _get_snapshot_with_client
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 165, in execute
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 54, in execute
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 280, in fetch_snapshot
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 134, in _get_snapshot_info
patch_common.exceptions.PatchManagerError: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 177, in <module>
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 172, in execute
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 111, in abort
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'
```

**Comment by rdksgit** [comment]
We are also facing the same issue, it looks like patch manager only supports till Debian 10, can Debian 11 be added to the supported list for patch manager

Thanks
Sameer

**Comment by chrisbloe** [comment]
Link to supported OSs: https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-prerequisites.html#:~:text=Debian%20Server%208.x%2C%209.x%2C%20and%2010.x

**Comment by warp3r** [comment]
Hi there, do we have any estimate on when Debian 11 will be supported by SSM?

Thanks!

**Comment by tonyjobson** [comment]
Any update on this

**Comment by freud44** [comment]
Hi folks
At this day, this is still unsupported.

**Comment by paulgear** [comment]
Should this be merged into https://github.com/aws/amazon-ssm-agent/issues/463?

**Comment by Chnwanze** [comment]
Debian 11 wasn't supported when this issue occurred, refer to [Patch manager Prerequisites](https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-prerequisites.html) for list of supported OSs.
