### ISSUE TITLE
Add Support for Rocky Linux 8.6

### ISSUE THREAD

**Issue by rodrigoSyscop** [aws/amazon-ssm-agent#457]
As per [AWS Systems Manager / Supported operating systems](https://docs.aws.amazon.com/systems-manager/latest/userguide/prereqs-operating-systems.html#w804aab5c21b9c23).

AWS is an official "Principal Sponsor" of Rocky Linux but SSM doesn't work: https://rockylinux.org/sponsors/

Add Support for Rocky Linux 8.6, available via official AWS Marketplace AMI: https://aws.amazon.com/marketplace/pp/prodview-2otariyxb3mqu

This is probably related to the issues #405, #414 and release [3.1.941.0](https://github.com/aws/amazon-ssm-agent/blob/mainline/RELEASENOTES.md#319410)

**Comment by rodrigoSyscop** [comment]
Here is the output of a _Patch Scan Only_ execution from one of my Rocky Linux 8.6 instances:

```
/usr/bin/python3
/usr/bin/yum
/usr/bin/dnf
Using python binary: 'python3'
Using Python Version: Python 3.6.8
/usr/bin/curl
/usr/bin/wget
07/31/2022 16:27:02 root [INFO]: Downloading payload from https://s3.dualstack.us-east-1.amazonaws.com/aws-ssm-us-east-1/patchbaselineoperations/linux/payloads/patch-baseline-operations-1.90.tar.gz
07/31/2022 16:27:03 root [INFO]: Attempting to import entrance file os_selector
07/31/2022 16:27:04 root [INFO]: Running with snapshot id = 3****-****-****-****-*****0 and operation = Scan
07/31/2022 16:27:04 botocore.credentials [INFO]: Found credentials in environment variables.
07/31/2022 16:27:04 root [ERROR]: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
    patch_snapshot = _get_snapshot_with_client(ssm_client, instance_id, snapshot_id, baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 420, in _get_snapshot_with_client
    SnapshotId=snapshot_id
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
07/31/2022 16:27:04 root [ERROR]: Error loading entrance module.
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
    patch_snapshot = _get_snapshot_with_client(ssm_client, instance_id, snapshot_id, baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 420, in _get_snapshot_with_client
    SnapshotId=snapshot_id
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 165, in execute
    exit(   entrance_module.execute(*argv))
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 55, in execute
    snapshot_id, override_list=override_list, baseline_override=baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 280, in fetch_snapshot
    snapshot_info = _get_snapshot_info(instance_id, snapshot_id, region, baseline_override_dict)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 134, in _get_snapshot_info
    raise PatchManagerError("Unsupported Operating System", ExitCodes.SNAPSHOT_UNSUPPORTED_OS, e)
patch_common.exceptions.PatchManagerError: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
07/31/2022 16:27:04 root [ERROR]: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
    patch_snapshot = _get_snapshot_with_client(ssm_client, instance_id, snapshot_id, baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 420, in _get_snapshot_with_client
    SnapshotId=snapshot_id
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 165, in execute
    exit(   entrance_module.execute(*argv))
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 55, in execute
    snapshot_id, override_list=override_list, baseline_override=baseline_override)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 280, in fetch_snapshot
    snapshot_info = _get_snapshot_info(instance_id, snapshot_id, region, baseline_override_dict)
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 134, in _get_snapshot_info
    raise PatchManagerError("Unsupported Operating System", ExitCodes.SNAPSHOT_UNSUPPORTED_OS, e)
patch_common.exceptions.PatchManagerError: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 
07/31/2022 16:27:04 root [ERROR]: unsupported operand type(s) for %: 'NoneType' and 'tuple'
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 126, in _get_snapshot_info
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 420, in _get_snapshot_with_client
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 357, in _api_call
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/client.py", line 661, in _make_api_call
botocore.errorfactory.UnsupportedOperatingSystem: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 165, in execute
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 55, in execute
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 280, in fetch_snapshot
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 134, in _get_snapshot_info
patch_common.exceptions.PatchManagerError: ('Unsupported Operating System', 146)
 Caused By: An error occurred (UnsupportedOperatingSystem) when calling the GetDeployablePatchSnapshotForInstance operation: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 179, in <module>
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 172, in execute
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 111, in abort
TypeError: unsupported operand type(s) for %: 'NoneType' and 'tuple'

```

**Comment by sluggard76** [comment]
We are working to support Rocky Linux 8.6

**Comment by rodrigoSyscop** [comment]
How about Rocky Linux 8.7?

**Comment by sluggard76** [comment]
You should be able to use SSM agent on Rocky Linux 8.6. Please note that Patching functionality is not yet supported. 

We have created a feature request to support Rocky Linux 8.7. Please note that we have a backlog of feature requests. We'll prioritize and work on those requests as they come in.
