### ISSUE TITLE
RPM fails to install with RedHat Image builder

### ISSUE THREAD

**Issue by signal15** [aws/amazon-ssm-agent#523]
The RPM works fine when manually installed.  However, when building an image with RedHat Image Builder, the following error occurs:

`error: Failed dependencies:
	/bin/sh is needed by amazon-ssm-agent-3.2.923.0-1.x86_64
Traceback (most recent call last):
  File "/run/osbuild/bin/org.osbuild.rpm", line 400, in <module>
    r = main(args["tree"], args["inputs"], args["options"])
  File "/run/osbuild/bin/org.osbuild.rpm", line 360, in main
    ], cwd=pkgpath, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['rpm', '--verbose', '--root', '/run/osbuild/tree', '--nosignature', '--install', '/tmp/manifest.ebfnfx_2']' returned non-zero exit status 254.`

**Comment by achilleas-k** [comment]
Hi.  I found this while looking into the same issue.
Have a look at https://github.com/osbuild/images/issues/2169
and
https://github.com/rpm-software-management/dnf/issues/2263

No solution yet, just reproducers.
