### ISSUE TITLE
Patching error on an Ubuntu 20.04 instance - AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by philm** [aws/amazon-ssm-agent#586]
SSM agent version: 3.3.551.0

Snippets from the CloudWatch logs output:

```
Using python binary: 'python3'
Using Python Version: Python 3.8.10

Downloading payload from https://s3.us-east-2.amazonaws.com/aws-ssm-us-east-2/patchbaselineoperations/linux/payloads/patch-baseline-operations-1.139.tar.gz

Attempting to import entrance file os_selector
Error loading entrance module.
Traceback (most recent call last):
  File "/var/log/amazon/ssm/patch-baseline-operations/common_startup_entrance.py", line 202, in execute
    entrance_module = __import__(module_name)
  File "/var/log/amazon/ssm/patch-baseline-operations/os_selector.py", line 11, in <module>
    import common_os_selector_methods
  File "/var/log/amazon/ssm/patch-baseline-operations/common_os_selector_methods.py", line 12, in <module>
    from patch_common.baseline_override import load_baseline_override
  File "/var/log/amazon/ssm/patch-baseline-operations/patch_common/baseline_override.py", line 6, in <module>
    from patch_common.downloader import download_file, load_json_file, is_access_denied
  File "/var/log/amazon/ssm/patch-baseline-operations/patch_common/downloader.py", line 14, in <module>
    from patch_common.client_selector import get_default_client
  File "/var/log/amazon/ssm/patch-baseline-operations/patch_common/client_selector.py", line 2, in <module>
    import boto3
  File "/var/log/amazon/ssm/patch-baseline-operations/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/var/log/amazon/ssm/patch-baseline-operations/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/awsrequest.py", line 25, in <module>
    import botocore.utils
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/utils.py", line 31, in <module>
    import botocore.httpsession
  File "/var/log/amazon/ssm/patch-baseline-operations/botocore/httpsession.py", line 17, in <module>
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext
  File "/var/log/amazon/ssm/patch-baseline-operations/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1571, in X509StoreFlags
    NOTIFY_POLICY = _lib.X509_V_FLAG_NOTIFY_POLICY

AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
```

**Comment by lvidaguren** [comment]
Looking similar error on certbot and ubuntu 20.04 I found this https://medium.com/@learning.by.playing.2023/problem-with-sudo-certbot-nginx-a6992bc1172e

wich proposes this solution

```
sudo apt remove python3-pip
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py

pip install pyopenssl --upgrade
```
otherwise upgrading to 22.04 or 24.04 I think would be the solution
