### ISSUE TITLE
TestSetConnectionChannel_MSGSuccess_MDSSwitchOff is flakey

### ISSUE THREAD

**Issue by arianvp** [aws/amazon-ssm-agent#587]
Noticed in NixOS that the test suite sometimes fails:

https://hydra.nixos.org/build/271623876

```
panic: test timed out after 20m0s
running tests:
        TestSetConnectionChannel_MGSSuccess_MDSSwitchOff (20m0s)

goroutine 4 [running]:
testing.(*M).startAlarm.func1()
        testing/testing.go:2366 +0x385
created by time.goFunc
        time/sleep.go:177 +0x2d

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000162b60, {0x89c45c?, 0x0?}, 0x8bf620)
        testing/testing.go:1750 +0x3ab
testing.runTests.func1(0xc000162b60)
        testing/testing.go:2161 +0x37
testing.tRunner(0xc000162b60, 0xc0001bfc60)
        testing/testing.go:1689 +0xfb
testing.runTests(0xc000124408, {0xfa82a0, 0x8, 0x8}, {0x415d10?, 0x41597a?, 0xfaf100?})
        testing/testing.go:2159 +0x445
testing.(*M).Run(0xc0003f6460)
        testing/testing.go:2027 +0x68b
main.main()
        _testmain.go:61 +0xa5

goroutine 21 [chan receive]:
github.com/aws/amazon-ssm-agent/agent/ssmconnectionchannel.TestSetConnectionChannel_MGSSuccess_MDSSwitchOff(0xc000162d00)
        github.com/aws/amazon-ssm-agent/agent/ssmconnectionchannel/ssmconnectionchannel_test.go:35 +0xb2
testing.tRunner(0xc000162d00, 0x8bf620)
        testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
        testing/testing.go:1742 +0x390
FAIL    github.com/aws/amazon-ssm-agent/agent/ssmconnectionchannel      1200.198s
ok      github.com/aws/amazon-ssm-agent/agent/task      0.267s
ok      github.com/aws/amazon-ssm-agent/agent/times     0.023s
ok      github.com/aws/amazon-ssm-agent/agent/update/processor  0.066s
ok      github.com/aws/amazon-ssm-agent/agent/update/tester     0.524s
ok      github.com/aws/amazon-ssm-agent/agent/update/updater    16.144s
ok      github.com/aws/amazon-ssm-agent/agent/updateutil        0.070s
ok      github.com/aws/amazon-ssm-agent/agent/updateutil/updateinfo     0.054s
ok      github.com/aws/amazon-ssm-agent/agent/updateutil/updatemanifest 0.054s
ok      github.com/aws/amazon-ssm-agent/agent/updateutil/updateprecondition/bottlerocket        0.018s
ok      github.com/aws/amazon-ssm-agent/agent/updateutil/updateprecondition/staticpie   0.057s
ok      github.com/aws/amazon-ssm-agent/agent/updateutil/updates3util   3.643s
ok      github.com/aws/amazon-ssm-agent/agent/versionutil       0.013s
FAIL
```

**Comment by Aperocky** [comment]
Fixed with https://github.com/aws/amazon-ssm-agent/commit/c2938e71481101c166035ebea343b7d5fa6fb747
